version: '3.0'
services:
  www:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./client:/var/www/html
      - w_dependencies:/usr/src/app/node_modules
    depends_on:
      - db
    ports:
      - "8080:3000"
  sv:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: sv
    restart: always
    volumes:
      - ./server:/var/www/html
      - sv_dependencies:/usr/src/app/node_modules
    depends_on:
      - db
    ports:
      - "8081:3001"
  snmp:
    build:
      context: ./snmp
      dockerfile: Dockerfile
    container_name: snmp
    restart: always
    volumes:
      - ./snmp:/var/www/html
      - sm_dependencies:/usr/src/app/node_modules
    depends_on:
      - db
  
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - "3306:3306"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    restart: always
    env_file:
      - ./config.env
    depends_on:
      - db
volumes:
    persistent:
    w_dependencies:
    sv_dependencies:
    sm_dependencies:


